# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DJUser' do
  pod 'Firebase/Core'
  # Required by RNFirebase
pod 'Firebase/Core', '~> 5.12.0'
pod 'Firebase/Auth', '~> 5.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DJUser

  # target 'DJUser-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # target 'DJUserTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

target 'DJUser-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DJUser-tvOS

  target 'DJUser-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
